all:
	make -C growth

r7:
	@vim growth/2018/07.tex

r8:
	@vim growth/2018/08.tex

r9:
	@vim growth/2018/09.tex

r10:
	@vim growth/2018/10.tex

r11:
	@vim growth/2018/11.tex

r12:
	@vim growth/2018/12.tex

r: r12
