all:
	make -C growth

r: r1

r1:
	@vim growth/2019/01.tex
	
r2:
	@vim growth/2019/02.tex

r3:
	@vim growth/2019/03.tex

r4:
	@vim growth/2019/04.tex

r5:
	@vim growth/2019/05.tex

r6:
	@vim growth/2019/06.tex

r7:
	@vim growth/2019/07.tex

r8:
	@vim growth/2019/08.tex

r9:
	@vim growth/2019/09.tex

r10:
	@vim growth/2019/10.tex

r11:
	@vim growth/2019/11.tex

r12:
	@vim growth/2019/12.tex

