all:
	cd src && xelatex main.tex && mv -f main.pdf ../ssan.pdf

r: r3

r1:
	vim src/history/2019/01.tex
	
r2:
	vim src/history/2019/02.tex

r3:
	vim src/history/2019/03.tex

r4:
	vim src/history/2019/04.tex

r5:
	vim src/history/2019/05.tex

r6:
	vim src/history/2019/06.tex

r7:
	vim src/history/2019/07.tex

r8:
	vim src/history/2019/08.tex

r9:
	vim src/history/2019/09.tex

r10:
	vim src/history/2019/10.tex

r11:
	vim src/history/2019/11.tex

r12:
	vim src/history/2019/12.tex

