all:
	cd src && xelatex main.tex && mv -f main.pdf ../lich.pdf

r8:
	vim src/history/2018/08.tex

r9:
	vim src/history/2018/09.tex

r10:
	vim src/history/2018/10.tex

r11:
	vim src/history/2018/11.tex

r12:
	vim src/history/2018/12.tex

r: r12
