all	: abstr.pdf \
	  datetime.pdf \
	  moremaths.pdf \
	  pagestyle.pdf \
	  spchar.pdf \
	  toc.pdf \
	  babel-sample.pdf \
	  figures.pdf \
	  mathssym.pdf \
	  renewcom.pdf \
	  subfloats.pdf \
	  vectors.pdf \
	  biblio.pdf \
	  fonts.pdf \
	  newcomopt.pdf \
	  section.pdf \
	  tables.pdf \
	  counters.pdf \
	  graphicx.pdf \
	  newcom.pdf \
	  simpledoc.pdf \
	  tabular.pdf \
	  crossref.pdf \
	  lists.pdf \
	  newenv.pdf \
	  simple.pdf \
	  title.pdf

abstr.pdf	: abstr.tex
	pdflatex abstr
	pdflatex abstr


babel-sample.pdf	: babel-sample.tex
	pdflatex babel-sample


biblio.pdf	: biblio.tex
	pdflatex biblio
	pdflatex biblio


counters.pdf	: counters.tex
	pdflatex counters
	pdflatex counters


crossref.pdf	: crossref.tex
	pdflatex crossref
	pdflatex crossref


datetime.pdf	: datetime.tex
	pdflatex datetime


figures.pdf	: figures.tex
	pdflatex figures
	pdflatex figures


fonts.pdf	: fonts.tex
	pdflatex fonts


graphicx.pdf	: graphicx.tex
	pdflatex graphicx


lists.pdf	: lists.tex
	pdflatex lists


moremaths.pdf	: moremaths.tex
	pdflatex moremaths
	pdflatex moremaths


mathssym.pdf	: mathssym.tex
	pdflatex mathssym
	pdflatex mathssym


newcomopt.pdf	: newcomopt.tex
	pdflatex newcomopt
	pdflatex newcomopt


newcom.pdf	: newcom.tex
	pdflatex newcom
	pdflatex newcom


newenv.pdf	: newenv.tex
	pdflatex newenv
	pdflatex newenv


pagestyle.pdf	: pagestyle.tex
	pdflatex pagestyle
	pdflatex pagestyle


renewcom.pdf	: renewcom.tex
	pdflatex renewcom
	pdflatex renewcom


section.pdf	: section.tex
	pdflatex section
	pdflatex section


simpledoc.pdf	: simpledoc.tex
	pdflatex simpledoc


simple.pdf	: simple.tex
	pdflatex simple


spchar.pdf	: spchar.tex
	pdflatex spchar


subfloats.pdf	: subfloats.tex
	pdflatex subfloats
	pdflatex subfloats


tables.pdf	: tables.tex
	pdflatex tables
	pdflatex tables


tabular.pdf	: tabular.tex
	pdflatex tabular


title.pdf	: title.tex
	pdflatex title
	pdflatex title


toc.pdf	: toc.tex
	pdflatex toc
	pdflatex toc


vectors.pdf	: vectors.tex
	pdflatex vectors
	pdflatex vectors

clean	:
	\rm -f *.{aux,log,lof,toc,lot,synctex.gz,fdb_latexmk}
