centos_deps:
	yum install -y libtool automake autoconf
	yum install -y flex bison
	yum install -y openssl-devel sqlite-devel libuuid-devel libaio-devel
	yum install -y python-paramiko
	yum install -y expect
	yum install -y redhat-lsb
	yum install -y gperftools
